version: "3.9"

services:
  postgres:
    image: postgres:17
    container_name: my-postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"

  wildfly:
    build: .
    container_name: my-wildfly
    ports:
      - "8080:8080"
      - "9990:9990"
    depends_on:
      - postgres
